// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_ping from "./routes/api/ping.ts";
import * as $api_private_middleware from "./routes/api/private/_middleware.ts";
import * as $api_private_admin_middleware from "./routes/api/private/admin/_middleware.ts";
import * as $api_private_admin_chargers from "./routes/api/private/admin/chargers.ts";
import * as $api_private_admin_new_charging_stations from "./routes/api/private/admin/new-charging-stations.ts";
import * as $api_private_admin_queues from "./routes/api/private/admin/queues.ts";
import * as $api_private_charging_flows_middleware from "./routes/api/private/charging-flows/_middleware.ts";
import * as $api_private_charging_flows_arrivals from "./routes/api/private/charging-flows/arrivals.ts";
import * as $api_private_charging_flows_established_sessions_middleware from "./routes/api/private/charging-flows/established-sessions/_middleware.ts";
import * as $api_private_charging_flows_established_sessions_charger_checkins from "./routes/api/private/charging-flows/established-sessions/charger-checkins.ts";
import * as $api_private_charging_flows_established_sessions_charging_end from "./routes/api/private/charging-flows/established-sessions/charging-end.ts";
import * as $api_private_charging_flows_established_sessions_charging_start from "./routes/api/private/charging-flows/established-sessions/charging-start.ts";
import * as $api_private_charging_flows_established_sessions_departures from "./routes/api/private/charging-flows/established-sessions/departures.ts";
import * as $api_private_shared_middleware from "./routes/api/private/shared/_middleware.ts";
import * as $api_private_shared_auction_offers_id_ from "./routes/api/private/shared/auction-offers/[id].ts";
import * as $api_private_shared_auction_offers_index from "./routes/api/private/shared/auction-offers/index.ts";
import * as $api_private_shared_auctions from "./routes/api/private/shared/auctions.ts";
import * as $api_private_shared_charging_stations from "./routes/api/private/shared/charging-stations.ts";
import * as $api_private_shared_fleets from "./routes/api/private/shared/fleets.ts";
import * as $api_private_shared_reservations from "./routes/api/private/shared/reservations.ts";
import * as $api_private_shared_sessions_id_ from "./routes/api/private/shared/sessions/[id].ts";
import * as $api_private_shared_users from "./routes/api/private/shared/users.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $partials_login_form from "./routes/partials/login-form.tsx";
import * as $partials_register_form from "./routes/partials/register-form.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $LoginRegisterSwitch from "./islands/LoginRegisterSwitch.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/api/ping.ts": $api_ping,
    "./routes/api/private/_middleware.ts": $api_private_middleware,
    "./routes/api/private/admin/_middleware.ts": $api_private_admin_middleware,
    "./routes/api/private/admin/chargers.ts": $api_private_admin_chargers,
    "./routes/api/private/admin/new-charging-stations.ts":
      $api_private_admin_new_charging_stations,
    "./routes/api/private/admin/queues.ts": $api_private_admin_queues,
    "./routes/api/private/charging-flows/_middleware.ts":
      $api_private_charging_flows_middleware,
    "./routes/api/private/charging-flows/arrivals.ts":
      $api_private_charging_flows_arrivals,
    "./routes/api/private/charging-flows/established-sessions/_middleware.ts":
      $api_private_charging_flows_established_sessions_middleware,
    "./routes/api/private/charging-flows/established-sessions/charger-checkins.ts":
      $api_private_charging_flows_established_sessions_charger_checkins,
    "./routes/api/private/charging-flows/established-sessions/charging-end.ts":
      $api_private_charging_flows_established_sessions_charging_end,
    "./routes/api/private/charging-flows/established-sessions/charging-start.ts":
      $api_private_charging_flows_established_sessions_charging_start,
    "./routes/api/private/charging-flows/established-sessions/departures.ts":
      $api_private_charging_flows_established_sessions_departures,
    "./routes/api/private/shared/_middleware.ts":
      $api_private_shared_middleware,
    "./routes/api/private/shared/auction-offers/[id].ts":
      $api_private_shared_auction_offers_id_,
    "./routes/api/private/shared/auction-offers/index.ts":
      $api_private_shared_auction_offers_index,
    "./routes/api/private/shared/auctions.ts": $api_private_shared_auctions,
    "./routes/api/private/shared/charging-stations.ts":
      $api_private_shared_charging_stations,
    "./routes/api/private/shared/fleets.ts": $api_private_shared_fleets,
    "./routes/api/private/shared/reservations.ts":
      $api_private_shared_reservations,
    "./routes/api/private/shared/sessions/[id].ts":
      $api_private_shared_sessions_id_,
    "./routes/api/private/shared/users.ts": $api_private_shared_users,
    "./routes/api/register.ts": $api_register,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/partials/login-form.tsx": $partials_login_form,
    "./routes/partials/register-form.tsx": $partials_register_form,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/LoginRegisterSwitch.tsx": $LoginRegisterSwitch,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
